<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>message_fileName</name>
   <tag></tag>
   <elementGuidId>489bce7b-2ac6-4ab3-9bc1-3a52e471a9d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='scrollableDiv']/div/div/div/div/li/div/div[2]/div/div/div/div[2]/p)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;5.03MB.docx&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>100a8e13-f27d-403d-a168-2d369cb3c774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-body1 !text-base cursor-default css-l6opbt</value>
      <webElementGuid>fb3b5447-b394-4d1b-820c-ae9919e9fec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>5.03MB.docx</value>
      <webElementGuid>ad7023d2-2cdf-4cca-ba1e-01fcfdf91c12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5.03MB.docx</value>
      <webElementGuid>4194a72f-44d2-47c4-bc6b-301013f33430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;min-h-full w-full h-svh max-h-svh flex flex-row flex-grow overflow-hidden MuiBox-root css-0&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-wrap-xs-nowrap css-a2e4ud&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-true h-full css-sui8tn&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-wrap-xs-nowrap css-1g8xl97&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-true !h-full !max-w-full !min-h-full css-sui8tn&quot;]/div[@class=&quot;bg-slate-200 h-full flex flex-col justify-between&quot;]/div[@id=&quot;scrollableDiv&quot;]/div[@class=&quot;infinite-scroll-component__outerdiv&quot;]/div[@class=&quot;infinite-scroll-component pb-4 pt-4 gap-y-4&quot;]/div[@class=&quot;MuiBox-root css-0&quot;]/div[@class=&quot;message-item-container flex space-x-2 items-start px-2 justify-end MuiBox-root css-0&quot;]/li[@class=&quot;MuiListItem-root MuiListItem-padding max-w-[70%] !justify-end css-13sbe1j&quot;]/div[@class=&quot;MuiStack-root css-qfdd9t&quot;]/div[@class=&quot;MuiStack-root justify-start css-l256j9&quot;]/div[@class=&quot;message-item-content h-full space-y-1&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 css-1tdosgn&quot;]/div[@class=&quot;MuiBox-root css-94mpuq&quot;]/div[@class=&quot;!line-clamp-2 MuiBox-root css-1rr4qq7&quot;]/p[@class=&quot;MuiTypography-root MuiTypography-body1 !text-base cursor-default css-l6opbt&quot;]</value>
      <webElementGuid>607b10b3-1fc8-42c6-9546-7b3439a988da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollableDiv']/div/div/div/div/li/div/div[2]/div/div/div/div[2]/p</value>
      <webElementGuid>7124cdb6-03f1-43bd-8fe2-2433f86943f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nguyễn Khang Hy Outlook'])[1]/following::p[2]</value>
      <webElementGuid>f9da79ff-a896-4e77-8495-2f45027ef118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nguyễn Khang Hy iCloud'])[1]/following::p[2]</value>
      <webElementGuid>279c7488-9390-48d0-8114-29ba4e9acd77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='hdhdhd'])[1]/preceding::p[4]</value>
      <webElementGuid>c1133d24-4fbf-4ff6-939c-f09ede2cd8e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Operations Analyst'])[1]/preceding::p[10]</value>
      <webElementGuid>0a40a874-9053-4374-b696-e76aac52aff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='5.03MB.docx']/parent::*</value>
      <webElementGuid>bae6b2db-9455-407e-a0dd-b6ce4364504b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p</value>
      <webElementGuid>2ee49715-694e-4609-bc8d-7c92ab5a36f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '5.03MB.docx' or . = '5.03MB.docx')]</value>
      <webElementGuid>62338a17-885b-4baa-9507-895ca628f076</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
