<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>message_image</name>
   <tag></tag>
   <elementGuidId>a8137ae5-8dbb-41d0-a703-0dd8ecf480e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-md-12.border.height-one.background.css-1uo6sxl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//li/div/div[2]/div/div/div/div/div)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#images-0690ab22-36e1-40ea-96be-e2d8d7436e07 > .MuiBox-root > div > .MuiGrid-root</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>763aa4ec-beb0-43cf-a63c-c663a14565a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12 MuiGrid-grid-md-12 border height-one background  css-1uo6sxl</value>
      <webElementGuid>9be3a062-5c1b-4e51-a182-2bdc5b8803be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;images-0690ab22-36e1-40ea-96be-e2d8d7436e07&quot;)/div[@class=&quot;MuiBox-root css-79elbk&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container container css-1d3bbye&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12 MuiGrid-grid-md-12 border height-one background  css-1uo6sxl&quot;]</value>
      <webElementGuid>7c59b2cb-a55c-4a8d-9b2e-6d02f51380a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='images-0690ab22-36e1-40ea-96be-e2d8d7436e07']/div/div/div</value>
      <webElementGuid>ac108e03-31d8-4558-bc32-b78137d244db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nguyễn Khang Hy Outlook'])[1]/following::div[21]</value>
      <webElementGuid>caa4c950-fb06-4917-a375-4676af7fa30c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nguyễn Khang Hy iCloud'])[1]/following::div[25]</value>
      <webElementGuid>0cbee779-c09a-4389-88c3-211a15955477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='hdhdhd'])[1]/preceding::div[10]</value>
      <webElementGuid>845d7929-58fa-4658-8463-f8bfa3bb5e31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Operations Analyst'])[1]/preceding::div[78]</value>
      <webElementGuid>7c9252bf-df30-46e6-bf13-3a0adb59cf80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div[2]/div/div/div/div/div</value>
      <webElementGuid>ec85c754-c971-486a-9d96-be691e857301</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
